### ISSUE TITLE
Можно ли обойтись без errorCheker ?

### ISSUE THREAD

**Issue by LuckyMillioner** [1deep1/c-code#2]
https://github.com/tRexSTYT/c-code/blob/0fa80067fa6e55394d27853e97d4daf4f3dfcc97/ProjectAssignment_1/errorChecker.c#L3

**Comment by 1deep1** [comment]
**errorCheker** - это обработка ошибок, без которой прожить можно и код будет работать без изменений, но это упрощает работу и с программой и с кодом. При всем при этом дальше код будет еще сложнее и без обработки ошибок ты захочешь убить себя. И код вынесен в отдельный файл, чтоб на засорять основной код и легче ориентироваться в проекте.
